---
- name: Install and configure tomcat
  hosts: webservers
  become: yes
  roles:
      - download_packages
      - install_java
      - install_tomcat
      - configure_tomcat
      - create_tomcat_service
