---
- name: Create Tomcat configuration directory
  shell: |
      mkdir -p /etc/tomcat10

- name: Configure Tomcat users
  template:
      src: tomcat-users.xml.j2
      dest: /etc/tomcat10/tomcat-users.xml
  notify: Restart Tomcat10
